### ISSUE TITLE
not all UnicodeData categories are mapped in glyphdata_generated

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#103]
The UnicodeData specification contains 30 categories:
http://www.unicode.org/L2/L1999/UnicodeData.html

They are all used by the `unicodedata` module, e.g.:
https://hg.python.org/cpython/file/tip/Modules/unicodedata_db.h#l606

However, the current `glyphsLib.glyphdata_generated.DEFAULT_CATEGORIES` mapping between UnicodeData categories and Glyphs.app categories only contains 28 entries.

By comparing the the two lists, it appears that the categories "Cc" (Other, Control) and "Cs" (Other, Surrogate) are missing from `DEFAULT_CATEGORIES`.

I suspect this fontmake issue is related to this:
https://github.com/googlei18n/fontmake/issues/234

I think the "Cc" unicodedata category should be assigned the Glyphs category "Separator", since that is what is assigned to the glyph "CR" (carriage return) in GlyphData.xml:

```xml
<glyph unicode="000D" name="CR" category="Separator" altNames="controlCR" description="CARRIAGE RETURN" />
```

I'm not sure about the Glyphs sub-category for the "Cc" control characters. Subcategory is missing in the example above, so I would say we leave it "None".

```python
"Cc": ('Separator', None),
```

I am not sure which Glyphs.app category should be assigned to "Cs" surrogate characters.
"Separator", or "Symbol", or what?

/cc @brawer

**Comment by anthrotype** [comment]
Given that the `glyphdata_generated` is indeed automatically generated, the issue should be somewhere in the `MetaTools/generate_glyphdata.py` script that builds the data.

The issue is present in the released glyphsLib==1.3.0, and currently affects all the Noto fonts that specify the carriage return glyph as "uni000D" instead of "CR":

```bash
cosimolupo@Cosimo-MBP ~/Documents/Github/noto-source (master) 
$ git grep -l 'glyphname = uni000D'
src/NotoSansMyanmar/NotoSansMyanmar-MM.glyphs
src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.glyphs
src/gNotoNastaliqUrdu.glyphs
src/gNotoSansBuginese.glyphs
src/gNotoSansCoptic.glyphs
src/gNotoSansGothic.glyphs
src/gNotoSansJavanese.glyphs
src/gNotoSansKayahLi.glyphs
src/gNotoSansLepcha.glyphs
src/gNotoSansMandaic.glyphs
src/gNotoSansMongolian.glyphs
src/gNotoSansNKo.glyphs
src/gNotoSansPhagsPa.glyphs
src/gNotoSansSamaritan.glyphs
src/gNotoSansSyriacEastern.glyphs
src/gNotoSansSyriacEstrangela.glyphs
src/gNotoSansSyriacWestern.glyphs
src/gNotoSansTaiLe.glyphs
src/gNotoSansTifinagh.glyphs
```

It can reproduced by simply calling `get_glyph` with `"uni000D"` as input:
```python
>>> from glyphsLib.glyphdata import get_glyph
>>> get_glyph('uni000D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cosimolupo/Documents/Github/glyphsLib/Lib/glyphsLib/glyphdata.py", line 42, in get_glyph
    category, subCategory = _get_category(name, unistr, data)
  File "/Users/cosimolupo/Documents/Github/glyphsLib/Lib/glyphsLib/glyphdata.py", line 76, in _get_category
    return data.DEFAULT_CATEGORIES[ucat]
KeyError: 'Cc'
```
