### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/glyphsLib#184]
Trying to convert `Cairo_V2.glyphs` file from https://github.com/Gue3bara/Cairo causes the following error:
```
$ glyphs2ufo -g sources/Cairo_V2.glyphs 
Traceback (most recent call last):
  File "/home/khaled/.local/bin/glyphs2ufo", line 11, in <module>
    sys.exit(main())
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/__main__.py", line 54, in main
    glyphsLib.build_masters(opt.glyphs, opt.masters)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/__init__.py", line 91, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/__init__.py", line 67, in load_to_ufos
    data = load(ifile)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/__init__.py", line 44, in load
    return loads(fp.read())
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/__init__.py", line 55, in loads
    cast_data(data)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 521, in cast_data
    _convert_data(data, True, _TYPE_STRUCTURE)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 537, in _convert_data
    _convert_data(cur_data, to_typed, cur_type)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 537, in _convert_data
    _convert_data(cur_data, to_typed, cur_type)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 537, in _convert_data
    _convert_data(cur_data, to_typed, cur_type)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 539, in _convert_data
    data[key] = cur_type.convert(data[key], to_typed)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 81, in convert
    return self.read(data) if to_typed else self.write(data)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 249, in read
    return _mutate_list(node.read, src)
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 76, in _mutate_list
    l[i] = fn(l[i])
  File "/home/khaled/.local/lib/python3.6/site-packages/glyphsLib/casting.py", line 213, in read
    x, y, node_type, smooth = self._regex.match(src).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by khaledhosny** [comment]
This seems to come from lines like this `"223 334 QCURVE SMOOTH",`, but the regex where the error happens does not check for `QCURVE`.
