### ISSUE TITLE
Cannot load Montserrat. Failed parsing

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/glyphsLib#238]
Hey folks,

Loading [Montserrat.glyphs](https://github.com/JulietaUla/Montserrat/tree/master/sources) using the latest commit produces the following traceback.

```
>>> font = glyphsLib.load(open('./Montserrat.glyphs', 'rb))
Traceback (most recent call last):
  File "test_montserrat.py", line 3, in <module>
    a = glyphsLib.load(open('/Users/marc/Documents/googlefonts/manual_font_cleaning/Montserrat/sources/Montserrat.glyphs', 'rb'))
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/__init__.py", line 48, in load
    return loads(fp.read())
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/__init__.py", line 57, in loads
    data = p.parse(s)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 44, in parse
    result, i = self._parse(text, 0)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 88, in _parse
    return self._parse_dict(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 132, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 147, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 94, in _parse
    return self._parse_list(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 174, in _parse_list
    list_item, i = self._parse(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 88, in _parse
    return self._parse_dict(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 132, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 147, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 88, in _parse
    return self._parse_dict(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 132, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 147, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/Users/marc/Documents/glyphsLib/Lib/glyphsLib/parser.py", line 115, in _parse
    value = self.dict_type(value)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

I'm guessing this has been introduced with the new class tree additions.

Apologies I can't delve deeper into this. 

For my own tools, I use the pip releases so I'm not affected by this.

**Comment by anthrotype** [comment]
thanks Marc. @belluzj could you take a look?

**Comment by belluzj** [comment]
Yes

**Comment by anthrotype** [comment]
thanks!

**Comment by belluzj** [comment]
I fixed the crash but there might something more to do: Montserrat has some [`GSInstance::instanceInterpolations`](https://docu.glyphsapp.com/#instanceInterpolations) with coefficients that look like `NSPoint`s rather than floats, e.g.

```
instanceInterpolations = {
UUID0 = "{0.777778, 0.733333}";
"1C84A7F3-C40A-4DC1-B8B4-102D183C348F" = "{0.222222, 0.266667}";
};
```

The commit that I just added parses those values as strings, but we should probably define more precisely what are the possible values of `instanceInterpolations` and parse them accordingly, maybe as points.

**Comment by m4rc1e** [comment]
Thank you for the quick turnaround here!

**Comment by schriftgestalt** [comment]
I answered that in #240.
