### ISSUE TITLE
cannot build noto with newest glyphslib

### ISSUE THREAD

**Issue by themaddoctor** [googlei18n/glyphsLib#242]
My glyphsLib is from git 20171016 (three days ago; last time changed).
Fontmake is 1.3.0.

Traceback (most recent call last):
File "/usr/bin/fontmake", line 11, in
load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
File "/usr/lib/python2.7/site-packages/fontmake/main.py", line 183, in main
project.run_from_glyphs(glyphs_path, **args)
File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
glyphs_path, family_name, mti_source=mti_source)
File "/usr/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
return func(*args, **kwds)
File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
family_name=family_name)
File "/usr/lib/python2.7/site-packages/glyphsLib/init.py", line 93, in build_masters
filename, include_instances=True, family_name=family_name)
File "/usr/lib/python2.7/site-packages/glyphsLib/init.py", line 72, in load_to_ufos
family_name=family_name, debug=debug)
File "/usr/lib/python2.7/site-packages/glyphsLib/builder.py", line 172, in to_ufos
layer_name = layer.name
File "/usr/lib/python2.7/site-packages/glyphsLib/classes.py", line 2349, in name
return master.name
File "/usr/lib/python2.7/site-packages/glyphsLib/classes.py", line 1297, in name
names.add("Italic")
AttributeError: 'list' object has no attribute 'add'

If I use python3 instead of 2:

==== building src/NotoSans-ItalicMM.glyphs ====
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
  File "/usr/lib/python3.6/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python3.6/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/usr/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/usr/lib/python3.6/site-packages/glyphsLib/__init__.py", line 93, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/usr/lib/python3.6/site-packages/glyphsLib/__init__.py", line 72, in load_to_ufos
    family_name=family_name, debug=debug)
  File "/usr/lib/python3.6/site-packages/glyphsLib/builder.py", line 115, in to_ufos
    if font.appVersion < 895:
TypeError: '<' not supported between instances of 'str' and 'int'

I also made this an issue in noto-source, just in case it would be relevant there, too.

**Comment by belluzj** [comment]
The first problem is still here, I will add a test and fix it.

The second problem has been fixed, the comparison now reads: "if int(font.appVersion) < 895:"

**Comment by themaddoctor** [comment]
For the first problem, changing names.add to names.append should fix it.


On 10/19/17, belluzj <notifications@github.com> wrote:
> The first problem is still here, I will add a test and fix it.
>
> The second problem has been fixed, the comparison now reads: "if
> int(font.appVersion) < 895:"
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/googlei18n/glyphsLib/issues/242#issuecomment-337952652


-- 
Thomas Kaeding

my public key: http://pgp.mit.edu/pks/lookup?op=get&search=0x81B0FCA32599BE6F

**Comment by belluzj** [comment]
Yes but I will also add a few tests because that method is not really covered: https://codecov.io/gh/googlei18n/glyphsLib/src/master/Lib/glyphsLib/classes.py#L1227
