### ISSUE TITLE
cannot build from source due to mismatched number of elements in glyph

### ISSUE THREAD

**Issue by themaddoctor** [googlei18n/glyphsLib#245]
Using the source from 20171012, and all tools are up to date:

==== building src/gNotoSansSyriacEastern.glyphs ====
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Loading to UFOs
INFO:glyphsLib.util:Writing master_ufo/NotoSansSyriacEastern-Regular.ufo
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:Reading master_ufo/NotoSansSyriacEastern-Regular.designspace
INFO:mutatorMath:	Generating instance NotoSansSyriacEastern-Regular.ufo
INFO:fontmake.font_project:Building OTFs
INFO:fontmake.font_project:Decomposing glyphs for NotoSansSyriacEastern-Regular
INFO:fontmake.font_project:Removing overlaps for NotoSansSyriacEastern-Regular
INFO:fontmake.font_project:Saving OTF for NotoSansSyriacEastern-Regular
Traceback (most recent call last):
  File "/usr/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake==1.3.0', 'console_scripts', 'fontmake')()
  File "/usr/lib/python2.7/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 378, in run_from_glyphs
    designspace_path, instance_data=instance_data, **kwargs)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 434, in run_from_designspace
    interpolate_layout_from=interpolate_layout_from, **kwargs)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 473, in run_from_ufos
    ufos, remove_overlaps, **kwargs)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 175, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/fontmake/font_project.py", line 295, in save_otfs
    font = compileOTF(ufo, optimizeCFF=subroutinize, **compiler_options)
  File "/usr/lib/python2.7/site-packages/ufo2ft/__init__.py", line 42, in compileOTF
    featureCompiler.compile()
  File "/usr/lib/python2.7/site-packages/ufo2ft/featureCompiler.py", line 39, in compile
    self.setupFile_features()
  File "/usr/lib/python2.7/site-packages/ufo2ft/featureCompiler.py", line 57, in setupFile_features
    features = self._findLayoutFeatures()
  File "/usr/lib/python2.7/site-packages/ufo2ft/featureCompiler.py", line 122, in _findLayoutFeatures
    doc = parser.parse()
  File "/usr/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 55, in parse
    statements.append(self.parse_feature_block_())
  File "/usr/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 1143, in parse_feature_block_
    self.parse_block_(block, vertical, stylisticset, size_feature)
  File "/usr/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 1225, in parse_block_
    statements.append(self.parse_substitute_())
  File "/usr/lib/python2.7/site-packages/fontTools/feaLib/parser.py", line 673, in parse_substitute_
    (len(glyphs), len(replacements)), location)
fontTools.feaLib.error.FeatureLibError: instance_ufo/NotoSansSyriacEastern-Regular.ufo/features.fea:382:1: Expected a glyph class with 160 elements after "by", but found a glyph class with 480 elements

**Comment by anthrotype** [comment]
The error looks like a source issue to me. Perhaps the file was the result of opening up a binary TTF in Glyphs.app and then saving it as *,glyphs file, with the features not correctly decompiled.

**Comment by anthrotype** [comment]
yes, I believe the files prefixed with "g" are those for which we don't have source files but only binary fonts.

**Comment by schriftgestalt** [comment]
The OTF parsing is sightly improved in 2.5. But complicated chaining substitutions are still a problem. We are working on a better solution but that will take some time.

**Comment by themaddoctor** [comment]
Also found this today:
```
INFO:fontmake.font_project:Saving OTF for NotoSans-SemiCondensedLightItalic
INFO:fontTools.ttLib.tables.otBase:Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 12, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
INFO:fontmake.font_project:Saving OTF for NotoSans-SemiCondensedItalic
```

**Comment by moyogo** [comment]
@themaddoctor That is normal for fonttools.

**Comment by themaddoctor** [comment]
The comments about OTF sources doesn't make any sense. There are no such files in the sources.

**Comment by moyogo** [comment]
@themaddoctor The gNoto* files were generated from OTF sources which are not in the repository.
