### ISSUE TITLE
'module' object has no attribute 'glyphdata' using to_ufos()

### ISSUE THREAD

**Issue by DavidRaymond** [googlei18n/glyphsLib#263]
I'm getting the following error:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import glyphsLib
>>> gfont = open("Andika-RB.glyphs", 'r')
>>> font = glyphsLib.load(gfont)
>>> ufos = ufos = glyphsLib.to_ufos(font)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder/__init__.py", line 43, in to_ufos
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder/builders.py", line 133, in masters
  File "build/bdist.linux-x86_64/egg/glyphsLib/builder/glyph.py", line 43, in to_ufo_glyph
AttributeError: 'module' object has no attribute 'glyphdata'
>>> 
```
This is with the latest download of glyphsLib.

**Comment by belluzj** [comment]
I'll look at it

**Comment by anthrotype** [comment]
just in time, thanks
