### ISSUE TITLE
ValueError: invalid literal for int() with base 16: '0394,2206'

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/glyphsLib#265]
Trying to build [Roboto-Arabic](https://github.com/Gue3bara/Roboto-Arabic) with fontmake gives me the following error:
```
$ fontmake -g sources/Roboto.glyphs -o otf
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib:Parsing .glyphs file
INFO:glyphsLib:Casting parsed values
Traceback (most recent call last):
  File "/home/khaled/.local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/python3.6/site-packages/fontmake/__main__.py", line 183, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/python3.6/site-packages/fontmake/font_project.py", line 376, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/python3.6/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/python3.6/site-packages/fontmake/font_project.py", line 77, in build_master_ufos
    family_name=family_name)
  File "/python3.6/site-packages/glyphsLib/__init__.py", line 89, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/python3.6/site-packages/glyphsLib/__init__.py", line 65, in load_to_ufos
    data = load(ifile)
  File "/python3.6/site-packages/glyphsLib/__init__.py", line 42, in load
    return loads(fp.read())
  File "/python3.6/site-packages/glyphsLib/__init__.py", line 53, in loads
    cast_data(data)
  File "/python3.6/site-packages/glyphsLib/casting.py", line 525, in cast_data
    _convert_data(data, True, _TYPE_STRUCTURE)
  File "/python3.6/site-packages/glyphsLib/casting.py", line 541, in _convert_data
    _convert_data(cur_data, to_typed, cur_type)
  File "/python3.6/site-packages/glyphsLib/casting.py", line 543, in _convert_data
    data[key] = cur_type.convert(data[key], to_typed)
  File "/python3.6/site-packages/glyphsLib/casting.py", line 82, in convert
    return self.read(data) if to_typed else self.write(data)
  File "/python3.6/site-packages/glyphsLib/casting.py", line 170, in read
    return int(src, 16)
ValueError: invalid literal for int() with base 16: '0394,2206'
```

Apparently caused by one of the glyphs having `unicode = "0394,2206";` and it seems glyphsLib does not like that.

**Comment by belluzj** [comment]
https://github.com/googlei18n/glyphsLib/issues/216
