### ISSUE TITLE
Parsing Glyphs V1 files

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/glyphsLib#275]
Whilst trying to load, https://github.com/googlefonts/TangerineFont/blob/master/sources/Tangerine_Bold.glyphs We get the following traceback

```
Traceback (most recent call last):
  File "generate_variable_fonts.py", line 241, in <module>
    main(sys.argv[1], sys.argv[2])
  File "generate_variable_fonts.py", line 217, in main
    mm_families_paths = find_mm_compatible_glyphs_files(path)
  File "generate_variable_fonts.py", line 64, in find_mm_compatible_glyphs_files
    glyphs_source = glyphsLib.load(glyphs_file)
  File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 228, in load
    return loads(fp.read())
  File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 238, in loads
    data = p.parse(s)
  File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 51, in parse
    result, i = self._parse(text, 0)
  File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 125, in _parse
    self._fail('Unexpected content', text, i)
  File "/Users/marc/Documents/googlefonts/variable_fonts/env/lib/python2.7/site-packages/glyphsLib/parser.py", line 221, in _fail
    raise ValueError('%s:\n%s' % (message, text[i:i + 79]))
ValueError: Unexpected content:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PL

```

I'm guessing the format changed in Glyphs V2? 

Could we not throw a better exception for this e.g `GlyphsLib can only load Glyphs V2 files`

**Comment by behdad** [comment]
This is in the optional XML format instead of the ASCII-plist-like one it seems? Shouldn't be hard to implement.

**Comment by anthrotype** [comment]
I would have been simpler in the previous parser implementation where the parser was generic and didn’t know about the GS classes.
Anyway yeah it’s doable but not high priority. You can resave the file with Glyphs 2.

**Comment by anthrotype** [comment]
(Because we could have just used plistlib in place of our own ascii-plist parser)

**Comment by behdad** [comment]
Well, yeah, that's why originally the parser was completely separate from the casting information...

**Comment by behdad** [comment]
Looks like the parser is still independent, no?

**Comment by anthrotype** [comment]
it's a hybrid. It can still parse into a normal OrderedDict without casting the strings; but if given a GSFont (which is the default) it parses and populate objects from classes module directly

**Comment by anthrotype** [comment]
not going to happen, I guess
