### ISSUE TITLE
Support/skip customParameter "Enforce Compatibility Check"

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/glyphsLib#384]
If I try and gen a .glyphs file with fontmake which has the 'Enforce Compatibility Check' customParam enabled, I get the following traceback: 

```
Traceback (most recent call last):
  File "/Users/marc/Documents/fontmake/venv2/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.5.0.dev0', 'console_scripts', 'fontmake')()
  File "/Users/marc/Documents/fontmake/Lib/fontmake/__main__.py", line 211, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marc/Documents/fontmake/Lib/fontmake/font_project.py", line 415, in run_from_glyphs
    mti_source=mti_source)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/marc/Documents/fontmake/Lib/fontmake/font_project.py", line 104, in build_master_ufos
    source.font.save(ufo_path)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/defcon/objects/font.py", line 766, in save
    self._saveLib(writer=writer, saveAs=saveAs, progressBar=progressBar)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/defcon/objects/font.py", line 863, in _saveLib
    self.saveLib(writer)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/defcon/objects/font.py", line 880, in saveLib
    writer.writeLib(libCopy)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/ufoLib/__init__.py", line 940, in writeLib
    self._writePlist(LIB_FILENAME, libDict)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/ufoLib/__init__.py", line 631, in _writePlist
    raise UFOLibError("The data for the file %s could not be written because it is not properly formatted." % fileName)
ufoLib.UFOLibError: The data for the file lib.plist could not be written because it is not properly formatted.

```

It gens fine when I delete the param.

This customParam is very glyphsapp specific. In the guide, https://glyphsapp.com/tutorials/creating-a-variable-font it says:

> Pro tip: You can check compatibility with View > Show Master Compatibility (Ctrl-Opt-Cmd-N), but as long as you do not have any instances defined (see step 4), Glyphs will tolerate outline incompatibility. In File > Font Info > Font, you can add a custom parameter called Enforce Compatibility Check, and Glyphs will connect masters even if there are no instances between them:

Can we just skip this custom param?

Here's the .glyphs file [RobotoSlab-ss05.txt](https://github.com/googlei18n/glyphsLib/files/2224324/RobotoSlab-ss05.txt)
(change .txt --> .glyphs)

cc @mjlagattuta

**Comment by m4rc1e** [comment]
Closing. Fake news

**Comment by madig** [comment]
So, what was going on?

**Comment by m4rc1e** [comment]
The attached glyphs file will not gen. I get the following traceback.


```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "RobotoSlab-ss05.glyphs" file into <GSFont>
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern1.u found in kerning rules.
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern1.u found in kerning rules.
Traceback (most recent call last):
  File "/Users/marc/Documents/fontmake/venv2/bin/fontmake", line 9, in <module>
    load_entry_point('fontmake==1.5.0.dev0', 'console_scripts', 'fontmake')()
  File "/Users/marc/Documents/fontmake/Lib/fontmake/__main__.py", line 211, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/Users/marc/Documents/fontmake/Lib/fontmake/font_project.py", line 415, in run_from_glyphs
    mti_source=mti_source)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/Users/marc/Documents/fontmake/Lib/fontmake/font_project.py", line 104, in build_master_ufos
    source.font.save(ufo_path)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/defcon/objects/font.py", line 766, in save
    self._saveLib(writer=writer, saveAs=saveAs, progressBar=progressBar)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/defcon/objects/font.py", line 863, in _saveLib
    self.saveLib(writer)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/defcon/objects/font.py", line 880, in saveLib
    writer.writeLib(libCopy)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/ufoLib/__init__.py", line 940, in writeLib
    self._writePlist(LIB_FILENAME, libDict)
  File "/Users/marc/Documents/fontmake/venv2/lib/python2.7/site-packages/ufoLib/__init__.py", line 631, in _writePlist
    raise UFOLibError("The data for the file %s could not be written because it is not properly formatted." % fileName)
ufoLib.UFOLibError: The data for the file lib.plist could not be written because it is not properly formatted.

```

**Comment by anthrotype** [comment]
we have to get rid of that bad, catch-all `try: ... except:` block in ufoLib's _writePlist. It only obfuscates the real error

**Comment by anthrotype** [comment]
```
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

I put this error in. It means that, if you want to serialize to XML strings which contain non-ASCII characters you have to use a `unicode` string, instead of a bytes string. Bytes strings are supported on python2.7 and treated as plist `<string>` elements but only if they contain ASCII chars.

So, thanks Marc. We have a bug somewhere in glyphsLib.

**Comment by anthrotype** [comment]
or it might even be that the source file contains invalid data, e.g. the string contains NULL or control characters which cannot be serialized to XML. We need to check

**Comment by m4rc1e** [comment]
Thanks Cosimo!

**Comment by anthrotype** [comment]
so. it is a unicode string, it's not bytes. The problem is that it contains control characters which are invalid in xml (they can't be escaped either), so our ufoLib.etree module refuses to write invalid XML.
I guess we can consider this a source issue. UfoLib is doing its job. I'll make sure the errors are not obfuscated. Maybe also i'll print the fist invalid char found. in this case it was `\x02`. Why would one want to write "START OF TEXT" (U+0002) inside a custom parameter string, I have no idea.

**Comment by m4rc1e** [comment]
Thanks for your swiftness @anthrotype. @mjlagattuta remove \x02 in your source.

**Comment by anthrotype** [comment]
the offending character is in the DisplayStrings entry inside the glyphs source. That's where Glyphs.app stores the the strings of text that is currently been displayed in the various open tabs. I'd suggest t oclose all the tabs before committing the glyphs source file. Reduces the changes of things like these happening.

**Comment by anthrotype** [comment]
so in the end it wasn't a deliberate user input, no custom parameter involved here. just the way glyphs.app stores these display strings as text in the glyphs source file, and the limitation of XML in serializing some control characters..
this makes me think though.. The NeXTStep or "old-style" property list format currently used by Glyphs.app should only contain ASCII text, anything beyond should be escaped. But here I see unescaped UTF-8 strings. :thinking:

**Comment by m4rc1e** [comment]
Thanks!

This is always something I've found peculiar about the .glyphs format, It remembers application state for the given file. Does .ufo have something similar?

**Comment by anthrotype** [comment]
not built-in, but you can dump anything you want to the UFO lib

**Comment by mjlagattuta** [comment]
When I closed the tab and everything ran smoothly I was thinking some odd character in the tab must have caused the error but had no idea why.

@anthrotype Thanks for clearing that up for me!

**Comment by schriftgestalt** [comment]
I’ll have a look at the file. I can’t download it right now because of bad internet.

**Comment by schriftgestalt** [comment]
I had a look at the file and it looks good to me. 

The .glyphs files can contain UTF-8. I mentioned it a few times. NSDocument usually escapes it but doesn't have a problem to read those files.
