### ISSUE TITLE
Updating GlyphsData.xml fails

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#402]
```
glyphsLib (master) $ venv/bin/python MetaTools/generate_glyphdata.py 
Traceback (most recent call last):
  File "MetaTools/generate_glyphdata.py", line 282, in <module>
    test_data(glyphs, data)
  File "MetaTools/generate_glyphdata.py", line 185, in test_data
    assert prod == g.production_name, (name, prod, g.production_name)
AssertionError: ('A-osage', 'u104B0', 'A-osage')
```

**Comment by madig** [comment]
It actually fails on a lot of things: [glyphdata-fail.txt](https://github.com/googlei18n/glyphsLib/files/2308016/glyphdata-fail.txt)

**Comment by madig** [comment]
Duh. I forgot to pass the `data` parameter in https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/glyphdata.py#L55. Still some failures.
