### ISSUE TITLE
Round-tripping single UFO: no axes defined in designspace

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#423]
1. `git clone https://github.com/daltonmaag/ubuntu`
2. `ufo2glyphs ubuntu/source/Ubuntu-R.ufo`
3. `glyphs2ufo ubuntu/source/Ubuntu.glyphs`
4. `ufo2glyphs ubuntu/source/Ubuntu.designspace`
```
Traceback (most recent call last):
  File "/Users/nikolaus/Entwicklung/glyphsLib/venv/bin/ufo2glyphs", line 11, in <module>
    load_entry_point('glyphsLib', 'console_scripts', 'ufo2glyphs')()
  File "/Users/nikolaus/Entwicklung/glyphsLib/Lib/glyphsLib/cli.py", line 241, in _ufo2glyphs_entry_point
    return main(args)
  File "/Users/nikolaus/Entwicklung/glyphsLib/Lib/glyphsLib/cli.py", line 145, in main
    return options.func(options)
  File "/Users/nikolaus/Entwicklung/glyphsLib/Lib/glyphsLib/cli.py", line 197, in ufo2glyphs
    designspace.read(designspace_file)
  File "/Users/nikolaus/Entwicklung/glyphsLib/venv/lib/python3.7/site-packages/fontTools/designspaceLib/__init__.py", line 1031, in read
    reader.read()
  File "/Users/nikolaus/Entwicklung/glyphsLib/venv/lib/python3.7/site-packages/fontTools/designspaceLib/__init__.py", line 675, in read
    self.readSources()
  File "/Users/nikolaus/Entwicklung/glyphsLib/venv/lib/python3.7/site-packages/fontTools/designspaceLib/__init__.py", line 792, in readSources
    sourceObject.location = self.locationFromElement(sourceElement)
  File "/Users/nikolaus/Entwicklung/glyphsLib/venv/lib/python3.7/site-packages/fontTools/designspaceLib/__init__.py", line 824, in locationFromElement
    elementLocation = self.readLocationElement(locationElement)
  File "/Users/nikolaus/Entwicklung/glyphsLib/venv/lib/python3.7/site-packages/fontTools/designspaceLib/__init__.py", line 831, in readLocationElement
    raise DesignSpaceDocumentError("No axes defined")
fontTools.designspaceLib.DesignSpaceDocumentError: No axes defined
```

**Comment by anthrotype** [comment]
Yeah that’s a feature

**Comment by anthrotype** [comment]
You need to define an axes element to use the current fonttools designspaceLib

**Comment by madig** [comment]
Hm. Should glyphs2ufo define one when there's just one master?

**Comment by anthrotype** [comment]
does that master have a location along some axis? If so, there needs to be a global axes definition.
