### ISSUE TITLE
Round trip ufo>glyphs>ufo fails with invalid literal for int()

### ISSUE THREAD

**Issue by DavidRaymond** [googlei18n/glyphsLib#455]
I created a .glyphs file using:
`ufo2glyphs AndikaMtihaniRoman.designspace --output-path dwr2.glyphs`
then attempted to go back to ufos with glyphs2ufo and got the following output:
```
$ glyphs2ufo dwr2.glyphs -m dwr1
Traceback (most recent call last):
  File "/usr/local/bin/glyphs2ufo", line 11, in <module>
    sys.exit(_glyphs2ufo_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/cli.py", line 189, in _glyphs2ufo_entry_point
    return main(args)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/cli.py", line 153, in main
    return options.func(options)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/cli.py", line 181, in glyphs2ufo
    generate_GDEF=options.generate_GDEF,
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/__init__.py", line 109, in build_masters
    font = GSFont(filename)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/classes.py", line 3194, in __init__
    p.parse_into_object(self, fp.read())
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 63, in parse_into_object
    i = self._parse_dict_into_object(res, text, 1)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 164, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 101, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 191, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 95, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 148, in _parse_dict
    i = self._parse_dict_into_object(res, text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 164, in _parse_dict_into_object
    result = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 101, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 191, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 123, in _parse
    value = self.current_type(value)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/types.py", line 317, in parse_color
    return int(src)
ValueError: invalid literal for int() with base 10: '255.0'
```
Looking in the .glyphs file, the 255.0 came in:
```{
color = (255.0, 0.0, 0.0, 128.0);
glyphname = LtnCapC;
production = C;
layers = (
{
```

I tried with glyphsLib 3.1.1 and 3.1.3.
The font I was testing with is [https://github.com/silnrsi/font-andika-mtihani](url)

**Comment by madig** [comment]
Can have a look tomorrow. In the meantime, does it also happen when running from Python 3?

**Comment by madig** [comment]
Got it, `round()` returns an int in Py3 and a float in Py2. Reading should then fail, as floats are invalid there. Preparing a fix.

Having a look at `year` later.

**Comment by madig** [comment]
Can't reproduce the year issue. Are you sure the UFO stores an integer and not a string?

**Comment by DavidRaymond** [comment]
Ah, yes, it was string in the test file.
Sorry to waste your time on that one.

**Comment by madig** [comment]
No worries, I love bugs that solve themselves 😬

**Comment by madig** [comment]
Tagged a new version.
