### ISSUE TITLE
problems exporting file

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#461]

**Comment by madig** [comment]
Please be more specific 😁

**Comment by schriftgestalt** [comment]
When I try to generate a .glyphs file I get this backtrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/fontmake/__main__.py", line 186, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python3.6/site-packages/fontmake/font_project.py", line 367, in run_from_glyphs
    glyphs_path, family_name, mti_source=mti_source)
  File "/usr/local/lib/python3.6/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/fontmake/font_project.py", line 71, in build_master_ufos
    family_name=family_name)
ValueError: not enough values to unpack (expected 3, got 2)
```

glyphsLib.build_masters() returns a name tuple Masters that has two fields but the caller expects three: `masters, designspace_path, instances = glyphsLib.build_masters(...)`.

**Comment by madig** [comment]
Huh. Is your fontmake up to date?

**Comment by schriftgestalt** [comment]
I just updated it. But maybe that didn't work.

**Comment by madig** [comment]
I'm asking because https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/font_project.py#L71 is outside the `build_master_ufos` function.

**Comment by schriftgestalt** [comment]
pip uninstall/install fixed it. Sorry.
