### ISSUE TITLE
glyphs2ufo: chokes on data folder restoration on Windows

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#464]
On Windows, nested files in the data/ folder may get different path slashes inserted, confusing `fs`.

1. Download [testufo.zip](https://github.com/googlei18n/glyphsLib/files/2586552/testufo.zip)
2. `ufo2glyphs 1.ufo`
3. `glyphs2ufo Test.glyphs`

```
Traceback (most recent call last):
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\Programs\Python\Python37\Scripts\glyphs2ufo.exe\__main__.py", line 9, in <module>
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\glyphsLib\cli.py", line 189, in _glyphs2ufo_entry_point
    return main(args)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\glyphsLib\cli.py", line 153, in main
    return options.func(options)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\glyphsLib\cli.py", line 181, in glyphs2ufo
    generate_GDEF=options.generate_GDEF,
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\glyphsLib\__init__.py", line 137, in build_masters
    source.font.save(ufo_path)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\defcon\objects\font.py", line 861, in save
    self.saveData(writer=writer, saveAs=saveAs, progressBar=progressBar)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\defcon\objects\font.py", line 996, in saveData
    self.data.save(writer, saveAs=saveAs, progressBar=progressBar)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\defcon\objects\dataSet.py", line 134, in save
    writer.writeBytesToPath("%s/%s" % ("data", fileName), data["data"])
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\fontTools\ufoLib\__init__.py", line 1012, in writeBytesToPath
    self.fs.setbytes(path, data)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\fs\base.py", line 1248, in setbytes

    with closing(self.open(path, mode="wb")) as write_file:
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\fs\osfs.py", line 594, in open
    _path = self.validatepath(path)
  File "c:\users\nikolaus.waxweiler\appdata\local\programs\python\python37\lib\site-packages\fs\base.py", line 1437, in validatepath
    raise errors.InvalidCharsInPath(path)
fs.errors.InvalidCharsInPath: path 'data/test\TSI3.ttx' contains invalid characters
```

**Comment by madig** [comment]
This actually looks like a `fs` issue. In `fs\base.py(1434)validatepath()`, it does this:

```
1434 ->         invalid_chars = typing.cast(six.text_type, meta.get("invalid_path_chars"))
1435            if invalid_chars:
1436                if set(path).intersection(invalid_chars):
1437                    raise errors.InvalidCharsInPath(path)
```
`invalid_chars` is a string containing no-go characters, among them `\\`, which of course is in `path` on Windows.

**Comment by anthrotype** [comment]
no, it's not a bug in fs. we must always use forward slashes when interacting with fs.

**Comment by madig** [comment]
Forward slashes are used in the .glyphs file. Investigating.

**Comment by anthrotype** [comment]
I think I've already fixed defcon and ufo2ft, we should do the same with glyphsLib

**Comment by anthrotype** [comment]
we need to document this somewhere (probably in fontTools.ufoLib), that UFOReader/UFOWriter readData, writeData, and removeData take a relative path (relative to the UFO/data directory) which may only contain forward slashes as path separators on either POSIX or Windows. That's how the underlying fs module works in that it abstracts away from the particularities of each specific filesystems. All filesystems use forward slashes period.

**Comment by madig** [comment]
Maybe make ufoLib explode violently on encountering `\\`.

**Comment by anthrotype** [comment]
no.. it's a valid non-path-separator character on POSIX

**Comment by madig** [comment]
On passing stuff to `fs`?

**Comment by anthrotype** [comment]
ah ok.. well it already raises its own exception, with a clear error message.

**Comment by anthrotype** [comment]
if you really want, we could catch InvalidCharsInPath exception and re-raise a more meaningful UFOLibError if it does contain backslash, suggesting to replace it with forward slash.
We can't simply find and replace here.
