### ISSUE TITLE
Parsing com.github.googlei18n.ufo2ft.filters crashes

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#505]
In lib.plist:

```
    <key>com.github.googlei18n.ufo2ft.filters</key>
    <array>
      <dict>
        <key>exclude</key>
        <array>
          <string>f_f_i</string>
          <string>f_f_l</string>
          <string>f_f</string>
          <string>fi</string>
          <string>fl</string>
        </array>
        <key>name</key>
        <string>propagateAnchors</string>
        <key>pre</key>
        <true/>
      </dict>
    </array>
```

```
Traceback (most recent call last):
  File "/home/nikolaus/.virtualenvs/cantarell/bin/ufo2glyphs", line 11, in <module>
    sys.exit(_ufo2glyphs_entry_point())
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/cli.py", line 259, in _ufo2glyphs_entry_point
    return main(args)
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/cli.py", line 161, in main
    return options.func(options)
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/cli.py", line 235, in ufo2glyphs
    object_to_read, minimize_ufo_diffs=options.no_preserve_glyphsapp_metadata
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/builder/__init__.py", line 135, in to_glyphs
    return builder.font
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/builder/builders.py", line 526, in font
    self.to_glyphs_master_attributes(source, master)
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/builder/masters.py", line 125, in to_glyphs_master_attributes
    self.to_glyphs_custom_params(ufo, master)
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/builder/custom_params.py", line 736, in to_glyphs_custom_params
    handler.to_glyphs(glyphs_proxy, ufo_proxy)
  File "/home/nikolaus/.virtualenvs/cantarell/lib64/python3.7/site-packages/glyphsLib/builder/custom_params.py", line 627, in to_glyphs
    glyphs_filter, is_pre = write_glyphs_filter(ufo_filter)
ValueError: too many values to unpack (expected 2)
```

**Comment by madig** [comment]
Fixed in master.
