### ISSUE TITLE
parser bug results in ValueError: unichr() arg not in range(0x110000)

### ISSUE THREAD

**Issue by felipesanches** [googlei18n/glyphsLib#55]
Steps to reproduce:

* Download this:
https://raw.githubusercontent.com/clauseggers/Inknut-Antiqua/master/Inknut%20Antiqua%20LATIN%20ONLY/Inknut%20Antiqua%20uprights%20124%20LATIN%20ONLY.glyphs

* try to load this glyphs file and it will crash with:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ ./fontbakery-fix-glyphs.py test3.glyphs 
>>> Parsing .glyphs file
Traceback (most recent call last):
  File "./fontbakery-fix-glyphs.py", line 30, in <module>
    data = glyphsLib.load(glyphs_file)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/__init__.py", line 36, in load
    return loads(fp.read())
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/__init__.py", line 45, in loads
    data = p.parse(value)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 40, in parse
    result, i = self._parse(text, 0)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 52, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 80, in _parse_dict
    res[name], i = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 58, in _parse
    return self._parse_list(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 101, in _parse_list
    list_item, i = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 52, in _parse
    return self._parse_dict(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 80, in _parse_dict
    res[name], i = self._parse(text, i)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 62, in _parse
    parsed, value = m.group(0), self._trim_value(m.group(1))
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 136, in _trim_value
    return Parser._unescape_re.sub(Parser._unescape_fn, value)
  File "/usr/local/lib/python2.7/dist-packages/glyphsLib/parser.py", line 125, in _unescape_fn
    return unichr(int(m.group(2)[2:], 16))
ValueError: unichr() arg not in range(0x110000) (wide Python build)
```

The reason for this is at line 68 of the glyphs file which starts with:

```
notes = "Added this \U2018case_devanagari\U2019 for automatic GSUB of Latin punctuation with my special \U2018Devangari-style\U2019 Latin punctuation,
```

As you can see here, both \U2018c as well as \U2018D are interpreted by the parser as if they were 20-bit hexadecimal values.

**Comment by jamesgk** [comment]
One solution is to simply re-save the source with the latest version of Glyphs, which should replace the escapes with their respective characters. If we want to support older sources though, I'm not sure if it's safe to assume that no hexadecimal escapes are >0xFFFF. @dougfelt, do you know?

**Comment by behdad** [comment]
> As you can see here, both \U2018c as well as \U2018D are interpreted by the parser as if they were 20-bit hexadecimal values.

That would be valid Unicode  The code is grabbing six letters, ie.  \U2018ca.  We can limit six-letter sequences to those starting with 10.  But proper fix, IMO, is to implement whatever Glyphs does.  Ie, if it always grabs four letters, we should do the same.  @schriftgestalt ?

**Comment by schriftgestalt** [comment]
Glyphs assumes 4 hex digits.
