### ISSUE TITLE
Not yet Python3-ready?

### ISSUE THREAD

**Issue by felipesanches** [googlei18n/glyphsLib#56]
While working on https://github.com/googlefonts/fontbakery/issues/754 I tried using glyphsLib with python 3.4 and got this crash:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ ./fontbakery-fix-glyphs.py test3.glyphs 
Traceback (most recent call last):
  File "./fontbakery-fix-glyphs.py", line 17, in <module>
    import glyphsLib
  File "/usr/local/lib/python3.4/dist-packages/glyphsLib/__init__.py", line 25, in <module>
    from glyphsLib.parser import Parser
  File "/usr/local/lib/python3.4/dist-packages/glyphsLib/parser.py", line 119
    _unescape_re = re.compile(ur'(\\0[0-7]{2})|(\\U[0-9a-fA-F]{4,6})')
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by anthrotype** [comment]
Python 3 syntax no longer support unicode _and_ raw string literals like `ur"test string"`.
I suggest using `from __future__ import unicode_literals`, to treat all string as unicode strings like in Python 3, and replacing `ur` with just `r` (for raw strings).
