### ISSUE TITLE
KeyError for (presumably) valid glyphs file

### ISSUE THREAD

**Issue by brawer** [googlei18n/glyphsLib#86]
GlyphsLib crashes when trying to load the [attached font](https://github.com/googlei18n/glyphsLib/files/651394/NotLikedByGlyphsLib.glyphs.zip). But Glyphs.app has no problem opening this file.

```
$ PYTHONPATH=Lib python Lib/glyphsLib/__main__.py -g NotLikedByGlyphsLib.glyphs
Traceback (most recent call last):
  File "Lib/glyphsLib/__main__.py", line 59, in <module>
    main(sys.argv[1:])
  File "Lib/glyphsLib/__main__.py", line 54, in main
    glyphsLib.build_masters(opt.glyphs, opt.masters)
  File "/home/sascha/src/glyphsLib/Lib/glyphsLib/__init__.py", line 88, in build_masters
    filename, include_instances=True, family_name=family_name)
  File "/home/sascha/src/glyphsLib/Lib/glyphsLib/__init__.py", line 67, in load_to_ufos
    family_name=family_name, debug=debug)
  File "/home/sascha/src/glyphsLib/Lib/glyphsLib/builder.py", line 142, in to_ufos
    ufo = ufos[layer_id]
KeyError: u'0A718E2F-231D-484E-9433-16A5230D2CE8'
```

**Comment by schriftgestalt** [comment]
The file is invalid but Glyphs seems to be able to load the file anyway.

The problem is that there are all but one masters are missing, but the layers are still there. Those layers show up as 'normal' extra layers in the only master but they are missing the 'associatedMasterID'.

**Comment by belluzj** [comment]
This font does not crash anymore in the current master, but instead generates a bunch of warnings thanks to https://github.com/googlei18n/glyphsLib/pull/291
